targets:
  $default:
    builders:
      freezed:
        options:
          build_extensions:
            ^lib/models/{{}}.dart: lib/gen/{{}}.freezed.dart
      source_gen|combining_builder:
        options:
          build_extensions:
            ^lib/models/{{}}.dart: lib/gen/{{}}.g.dart
